In [4]:
!conda install -y gputil

done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.1
  latest version: 23.11.0

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /opt/conda/envs/tf_gpu_env

  added / updated specs:
    - gputil


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    gputil-1.4.0               |     pyh9f0ad1d_0          10 KB  conda-forge
    ------------------------------------------------------------
                                           Total:          10 KB

The following NEW packages will be INSTALLED:

  gputil             conda-forge/noarch::gputil-1.4.0-pyh9f0ad1d_0



gputil-1.4.0         | 10 KB     | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done


In [5]:
conda install -y psutil

done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.1
  latest version: 23.11.0

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /opt/conda/envs/tf_gpu_env

  added / updated specs:
    - psutil


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    psutil-5.9.7               |   py39hd1e30aa_0         354 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         354 KB

The following packages will be UPDATED:

  psutil              anaconda::psutil-5.9.0-py39h5eee18b_0 --> conda-forge::psutil-5.9.7-py39hd1e30aa_0



psutil-5.9.7         | 354 KB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may ne

In [6]:
import GPUtil

gpus = GPUtil.getGPUs()
for gpu in gpus:
    print(f"GPU: {gpu.name}")
    print(f"GPU Load: {gpu.load * 100}%")
    print(f"GPU Memory Free: {gpu.memoryFree}MB")
    print(f"GPU Memory Used: {gpu.memoryUsed}MB")
    print(f"GPU Memory Total: {gpu.memoryTotal}MB")
    print(f"GPU Temperature: {gpu.temperature} °C")
    print("-" * 40)

GPU: NVIDIA GeForce GTX 1070
GPU Load: 0.0%
GPU Memory Free: 27.0MB
GPU Memory Used: 8080.0MB
GPU Memory Total: 8192.0MB
GPU Temperature: 31.0 °C
----------------------------------------


In [7]:
import psutil

for proc in psutil.process_iter(['pid', 'name', 'memory_info']):
    print(proc.info)

{'pid': 1, 'name': 'conda', 'memory_info': pmem(rss=7720960, vms=31166464, shared=7077888, text=2355200, lib=0, data=17940480, dirty=0)}
{'pid': 7, 'name': 'bash', 'memory_info': pmem(rss=3276800, vms=7680000, shared=3276800, text=913408, lib=0, data=581632, dirty=0)}
{'pid': 17, 'name': 'bash', 'memory_info': pmem(rss=3407872, vms=7544832, shared=3276800, text=913408, lib=0, data=446464, dirty=0)}
{'pid': 20, 'name': 'conda_jupyterla', 'memory_info': pmem(rss=3407872, vms=7544832, shared=3276800, text=913408, lib=0, data=446464, dirty=0)}
{'pid': 34, 'name': 'jupyter-lab', 'memory_info': pmem(rss=41963520, vms=637595648, shared=17039360, text=2355200, lib=0, data=147251200, dirty=0)}
{'pid': 42, 'name': 'python', 'memory_info': pmem(rss=16785408, vms=766574592, shared=15204352, text=2355200, lib=0, data=140623872, dirty=0)}
{'pid': 77, 'name': 'python', 'memory_info': pmem(rss=16572416, vms=766574592, shared=15204352, text=2355200, lib=0, data=140410880, dirty=0)}
{'pid': 110, 'name':

### nvidia-smi 

* The output of nvidia-smi on the terminal is:

```
nvidia-smi
Sat Jan 20 19:00:16 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.146.02             Driver Version: 535.146.02   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1070        Off | 00000000:01:00.0 Off |                  N/A |
| 27%   31C    P8               5W / 151W |   8080MiB /  8192MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1037      G   /usr/lib/xorg/Xorg                            9MiB |
|    0   N/A  N/A      1243      G   /usr/bin/gnome-shell                          3MiB |
|    0   N/A  N/A      7914      C   /opt/conda/envs/tf_gpu_env/bin/python      5088MiB |
|    0   N/A  N/A     25839      C   /opt/conda/envs/tf_gpu_env/bin/python      2974MiB |
+---------------------------------------------------------------------------------------+
```

In [8]:
import psutil

# List of PIDs to investigate (from your nvidia-smi output)
pids_to_investigate = [1037, 1243, 7914, 25839]

for pid in pids_to_investigate:
    try:
        process = psutil.Process(pid)
        print(f"PID: {pid}")
        print(f"Name: {process.name()}")
        print(f"Executable: {process.exe()}")
        print(f"Command Line: {process.cmdline()}")
        print(f"Memory Info: {process.memory_info()}")
        print("-" * 40)
    except psutil.NoSuchProcess:
        print(f"Process with PID {pid} not found.")

Process with PID 1037 not found.
Process with PID 1243 not found.
Process with PID 7914 not found.
Process with PID 25839 not found.


### Use Terminal to Identify Tasks

* If we use the ps command on terminal, we get:

```
patrick@hpomen:~/Documents/gpu-jupyter-tensorflow$ ps 7914
    PID TTY      STAT   TIME COMMAND
   7914 ?        Ssl    6:46 /opt/conda/envs/tf_gpu_env/bin/python -m ipykernel_launcher -f /home/jovyan/.local/share/jupyter/runtime/kernel-c44cb665-0212-49e7-912b-92e80ec99262.json

patrick@hpomen:~/Documents/gpu-jupyter-tensorflow$ ps 25839
    PID TTY      STAT   TIME COMMAND
  25839 ?        Ssl    2:20 /opt/conda/envs/tf_gpu_env/bin/python -m ipykernel_launcher -f /home/jovyan/.local/share/jupyter/runtime/kernel-ace0f66f-d35b-435c-b241-bebd8c00f66e.json
```

